# Generated by Django 5.1.2 on 2024-12-09 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecom_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
    ]
