# Generated by Django 5.1.2 on 2024-12-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecom_app", "0002_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="big_description",
            field=models.TextField(blank=True, default="", max_length=1000, null=True),
        ),
    ]
